# Generated by Django 5.0 on 2024-01-12 03:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_herobanner_options_alter_movieslist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieslist',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
