# Generated by Django 5.0 on 2024-01-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_movieslist_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='movieslist',
            name='genres',
            field=models.ManyToManyField(related_name='Genres', to='api.genres'),
        ),
    ]
