# Generated by Django 5.0 on 2024-01-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_genres_movieslist_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieslist',
            name='mediatype',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
