# Generated by Django 5.0 on 2024-01-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_movieslist_mediatype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieslist',
            name='mediatype',
            field=models.CharField(choices=[('1', 'movies'), ('2', 'Shows')], max_length=30, null=True),
        ),
    ]
