# Generated by Django 5.0 on 2024-01-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_movieslist_mediatype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieslist',
            name='mediatype',
            field=models.CharField(choices=[('movies', 'movies'), ('Shows', 'Shows')], default='1', max_length=30),
        ),
    ]
