# Generated by Django 5.0 on 2024-01-12 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_movieslist_mediatype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieslist',
            old_name='rate',
            new_name='rating',
        ),
    ]
