# Generated by Django 5.0 on 2024-01-12 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_rate_movieslist_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieslist',
            name='popularity',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
